"""Abstract store interface for in-memory or Postgres backends."""

from abc import ABC, abstractmethod
from typing import Optional


class Store(ABC):
    """Abstract base class for data storage."""

    @abstractmethod
    def get_project(self, project_id: str): ...
    @abstractmethod
    def list_projects(self): ...
    @abstractmethod
    def create_project(self, project): ...
    @abstractmethod
    def delete_project(self, project_id: str): ...

    @abstractmethod
    def get_sample(self, sample_id: str): ...
    @abstractmethod
    def list_samples(self, project_id: Optional[str] = None): ...
    @abstractmethod
    def create_sample(self, sample): ...
    @abstractmethod
    def resolve_sample(self, sample_id: str):
        """Resolve sample by either internal PK or human-readable ID."""

    @abstractmethod
    def get_run(self, run_id: str): ...
    @abstractmethod
    def list_runs(self, project_id: Optional[str] = None): ...
    @abstractmethod
    def create_run(self, run): ...

    @abstractmethod
    def get_step(self, step_id: str): ...
    @abstractmethod
    def list_steps(self, run_id: str): ...
    @abstractmethod
    def create_step(self, step): ...
    @abstractmethod
    def update_step(self, step_id: str, **kwargs): ...

    @abstractmethod
    def list_events(self, run_id: str): ...
    @abstractmethod
    def create_event(self, event): ...

    @abstractmethod
    def list_logs(self, run_id: str): ...
    @abstractmethod
    def create_log(self, log): ...

    @abstractmethod
    def list_variants(self, sample_id: Optional[str] = None, run_id: Optional[str] = None): ...
    @abstractmethod
    def create_variant(self, variant): ...
    @abstractmethod
    def get_variant(self, variant_id: str): ...
    @abstractmethod
    def delete_variants_for_run(self, run_id: str): ...

    @abstractmethod
    def list_alignment_metrics(self, run_id: Optional[str] = None): ...
    @abstractmethod
    def create_alignment_metrics(self, metrics): ...

    @abstractmethod
    def list_coverage_metrics(self, run_id: Optional[str] = None): ...
    @abstractmethod
    def create_coverage_metrics(self, metrics): ...

    @abstractmethod
    def list_structural_variants(self, sample_id: Optional[str] = None): ...
    @abstractmethod
    def create_structural_variant(self, sv): ...

    @abstractmethod
    def list_cnv_segments(self, sample_id: Optional[str] = None): ...
    @abstractmethod
    def create_cnv_segment(self, cnv): ...

    @abstractmethod
    def list_taxonomy_hits(self, sample_id: Optional[str] = None): ...
    @abstractmethod
    def create_taxonomy_hit(self, hit): ...

    @abstractmethod
    def list_reports(self, run_id: Optional[str] = None): ...
    @abstractmethod
    def create_report(self, report): ...

    @abstractmethod
    def list_references(self): ...
    @abstractmethod
    def get_reference(self, ref_id: str): ...
